# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RE India
name: Apoorva Santhosh
email: apurvagreen@gmail.com
phone: +91 9863718876
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur 
  adipiscing elit, sed do eiusmod tempor incididunt ut 
  labore et dolore magna aliqua. Ut enim ad minim veniam,  
  nostrud exercitation 
baseurl: "/REIndia" # the subpath of your site, e.g. /blog
url: "http://code-mage.github.io/REIndia" # the base hostname & protocol for your site
twitter_username: allizad
github_username:  allizad
# include: ['_states']

# Build settings
markdown: kramdown
# source: src
# destination: public
